### ISSUE TITLE
Still disconnected after logging in

### ISSUE THREAD

**Issue by Keith94** [schomery/feedly-notifier-plus#1]
In Firefox 54, I installed the add-on, clicked the toolbar button, signed into Feedly, and refreshed the page manually, but the button is still gray and shows (disconnected) in tooltip.

**Comment by teemue** [comment]
I confirm. FF 52.0.1

**Comment by Keith94** [comment]
I use Feedly Notifier instead: https://olsh.me/Feedly-Notifier/
